### ISSUE TITLE
New Brightway logo

### ISSUE THREAD

**Issue by cmutel** [Depart-de-Sentier/Prizes#1]
# Summary

The existing Brightway2 logo is tightly integrated with the number 2, and a bit goofy. We need a new logo, for "Brightway" or "brightway", not "Brightway2."

Keywords for inspiration:

* Technical
* Modular
* Engineering
* Sustainability

# Prize Amount

100 € or CHF

# Output

* A logo, developed in iteration (within this issue) with @cmutel and other DdS staff, and provided in both vector and raster (multiple sizes) formats, including both black & white and colored versions, provided as a PR to this repository.
* Logo color scheme as a graphic and text file with hex and RGB codes.

# Verification

Verification will be done by @cmutel, who will provide feedback during the iterative design process.

**Comment by BenPortner** [comment]
The current logo for reference:
![image](https://user-images.githubusercontent.com/52913510/157468802-393a4044-fd37-4c40-b02a-66e0621d940b.png)

**Comment by LisaDuval** [comment]
Hi, maybe I could help ! Could you share a little more detail about what you would like, if you already have an idea ?

More precisely :
Do you want to keep the entire name in the logo ?
Do you want the little monster with the big smile to stay or not ?
Do you have a graphic charter specifying colors, font, etc... to use ?

Thank you !

**Comment by cmutel** [comment]
@LisaDuval Thanks a lot for your interest!

> Do you want to keep the entire name in the logo ?

Not necessarily, the name is long. Could be abbreviated to BW or even a logo without text, though then I would like to have a version with the name and a choice of font (I only say this because I know if it is left up to me it will be a disaster).

> Do you want the little monster with the big smile to stay or not ?

No, this was just a spur of the moment thing which is reached its end of life. However, I am completely open to something a bit quirky.

> Do you have a graphic charter specifying colors, font, etc... to use ?

No. There will be another prize after https://github.com/Depart-de-Sentier/Prizes/issues/2 is closed to design a new website identity with colors and fonts, but this will follow the ideas in the logo.

**Comment by cmutel** [comment]
Marking this as reserved for @LisaDuval for the time being.

**Comment by levonamatuni** [comment]
I might b able to contribute with the logo from my talented friend! :)
Is there a deadline for the PR submission?

**Comment by cmutel** [comment]
@levonamatuni There is no deadline. There are things that come after this, so sooner is better, but it is certainly not urgent.

**Comment by cmutel** [comment]
@levonamatuni @LisaDuval Another point of inspiration could be one of the origins for the name "Brightway", which was the pilgrimage path [Camino de Santiago](https://en.wikipedia.org/wiki/Camino_de_Santiago), called "Jakobsweg" in German. Ideas of paths, maps, and movement would all fit nicely.

**Comment by LisaDuval** [comment]
Nice to have this information ! I will try to propose some ideas on monday or before.

**Comment by LisaDuval** [comment]
Hello ! 

So here are some ideas I have been thinking about ! Nothing completely finished, especially colors and fonts, but I made some tests to have a glimpse of what it could become. 

**First idea** 

I focused on the letters "B" and "W", tried to customize it a bit. The leave is for the sustainability aspect, and the idea of the path is between the two letters (but I missed my shot if you did not see it). Maybe there is not enough of the "technique" aspect in this version.

![Concept 1](https://user-images.githubusercontent.com/94999377/158276656-0095ff05-2d87-45cc-bc7d-d71ba988f37d.png)

**Second idea**

The "BW" letters again, definitely more about technique/engineering, technology... Also more basic. I tried some neon light effect for the first time, so I think I can improve it if it corresponds to what you would want.

![Concept 2](https://user-images.githubusercontent.com/94999377/158277913-bad20b93-7743-4059-b546-518a4b444a99.png)

**Third idea**

It comes from [this image on internet](https://www.shutterstock.com/image-vector/way-green-logo-1233649453), which I found perfect for the sustainability and the path ideas. I redrew it and tried to modify it a little. 

![Concept 3](https://user-images.githubusercontent.com/94999377/158278476-093f9bf7-a10f-43cf-8933-ec5e765f8737.png)

Finally, a little bonus that I thought about 5 minutes ago :

![Concept 4](https://user-images.githubusercontent.com/94999377/158278518-66962301-a5cb-42c0-9805-7e55fc6847f4.png)

Every color, effect and font can be mixed with one of the version above. Waiting for your suggestions !

**Comment by cmutel** [comment]
Thanks a lot @LisaDuval! They are all nice - I would like to iterate on the leaf as a graph network idea, as this has some meaning for Brightway. Please let me see if I can use some real data to generate the graph nodes and edges in a leaf-ish form. I also think maybe we can make the path implicit instead of explicit, but this depends on how the data looks like.

**Comment by tngTUDOR** [comment]
[:sunglasses: ](https://peps.python.org/pep-0020/)

**Comment by tngTUDOR** [comment]
I don't know how I would go around shaping a graph as a "leaf", but @cmutel  your comment made me think of the "heart" layout for graphs using a specific algorithm (gursoy atun). Boost has something about [it here](https://www.boost.org/doc/libs/1_55_0/libs/graph/doc/gursoy_atun_layout.html).

**Comment by cmutel** [comment]
@LisaDuval I have already spent too much time on this (the exact opposite of the intent of paying others to do things I am not good at!), and without any useful output.

Could you please iterate on the leaf as graph idea with an ash leaf ([like shown here](https://www.woodlands.co.uk/blog/tree-identification/ash/)), without the path being so clearly delineated, and with the following variants:

- The main veins of the leaf having a higher thickness (weight) - this could be a way of showing the paths without being too obvious
- The same thing, but with different weights for different paths, i.e. a bit irregular
- A graph with all edges having an equal weight, but with the path shown by edges of a different color (the path shouldn't be too straight a line, it can bounce back and forth)

**Comment by LisaDuval** [comment]
Hi ! Sorry for the delay, but I had very busy weeks lately... I will try to propose something before the end of the week !

**Comment by cmutel** [comment]
Bumping amount to 100 CHF/Euros

**Comment by LisaDuval** [comment]
Hi !

I begin to have something interesting with the shape of the ash leaf. However, the path is maybe too clearly defined compared to what you imagined, because it is not really in the tiny leaves, but more into the general shape. I thought maybe the first version of the leaf in the upper part, close to the picture you sent, could be too big, so I tried below a shorter one.

I havent tried every variant yet ; but you can already tell me your general opinion and major modifications about the shape, complexity, etc... 

![Ash leaf +](https://user-images.githubusercontent.com/94999377/162020658-e450cf29-01f0-4f56-a319-412885bb80f9.png)

**Comment by cmutel** [comment]
@LisaDuval I love it! It isn't what I had in mind, but better.

I can't tell the difference between the left and right - just the line weights, or are the shapes also different? Either would work well, but I wonder if you could please also delete 1/3 - 1/2 of the interior lines in the leaves (at random) to see what that is like. We want it to be simultaneously a leaf and a network, from a distance it is maybe too much on the spectrum towards a leaf.

@aleksandra-kim @tngTUDOR @KarinTreyer @xiaoshir Would love to get some feedback from you :)

**Comment by xiaoshir** [comment]
I also find it is too leaf-like. Have you tried something like [this](https://looka.com/?gclid=Cj0KCQjwl7qSBhD-ARIsACvV1X2D_UE8g3Pdc4db6dyqEBgN_h2yVaDx0XdTODP1nG_eA1_IQs3UXxMaAlX5EALw_wcB) to design a logo? You can first narrow it down to a type of look based on the themes of your logo (eg. software, network), and then search for "leaf". It will give you hundreds of options for different leaves. Below is an example it makes: 
![image](https://user-images.githubusercontent.com/28433916/162141436-76d82eff-20f0-41a1-91b2-7be5a5163f27.png)

**Comment by LisaDuval** [comment]
Ok, so I simplified way more the leaf and I think it works better this way. Here an example without colors and with a first try with colors, just to imagine better what it could look like :


![BW ash leaf final](https://user-images.githubusercontent.com/94999377/162273156-9f2a4561-9033-42ba-b528-a93040de96e6.png)

![BW ash leaf col](https://user-images.githubusercontent.com/94999377/162273162-11815e0d-1953-476c-89af-9eeb65a735de.png)


@xiaoshir very good idea to use online logo generators. I think it is a good way to find inspiration, and if your team find something that better suits than my propositions, fell absolutely free to use it ! I am just offering my free time because I enjoy drawing :)

**Comment by cmutel** [comment]
@LisaDuval That's perfect. Please prepare a package with the logo on the left in various formats (native file format, raster, and vector), in both color and BW, and provide the font name. Please also email me with you location and preferred payment method.

**Comment by LisaDuval** [comment]
Hi ! 

I just need another feedback as I made some modifications :

- I made the lines of the leaf **thicker** to make it more logo-like and visible from afar
- I **homogenized** the size of the tiny leaves
- I added another variant with a **catching phrase**, as proposed above. If you like it and if necessary, the text can be changed.
- As I was not fully conviced with the **font**, I propose here another one. Both are free for commercial use. I supposed the font could be used in the website as well, so I added a preview of what it would look like as a text, it is a copy-paste from the Brightway 2 description.

Versions with the font **Roboto** ([download here](https://fonts.google.com/specimen/Roboto)), the first font I chose :

![Roboto versions](https://user-images.githubusercontent.com/94999377/162551631-b3654eaa-4047-462f-995d-039ff48ced0a.jpg)
![image](https://user-images.githubusercontent.com/94999377/162551732-a3e76d37-668b-4414-b49d-1c358d939666.png)

Versions with the font **Cuyabara** ([download here](https://www.dafont.com/cuyabra.font)), the new one :

![Cuyabara versions](https://user-images.githubusercontent.com/94999377/162551674-340bebe0-d1d3-4ba8-8050-e357e0a27db9.jpg)
![image](https://user-images.githubusercontent.com/94999377/162551745-db14606f-5e13-476a-a60c-7637c8c80e43.png)

In the end, please let me know the font you chose, and if I add the version with the catching phrase in the final package ! Every file will be there in the formats you specified.

**Comment by xiaoshir** [comment]
> Ok, so I simplified way more the leaf and I think it works better this way. Here an example without colors and with a first try with colors, just to imagine better what it could look like :
> 
> ![BW ash leaf final](https://user-images.githubusercontent.com/94999377/162273156-9f2a4561-9033-42ba-b528-a93040de96e6.png)
> 
> ![BW ash leaf col](https://user-images.githubusercontent.com/94999377/162273162-11815e0d-1953-476c-89af-9eeb65a735de.png)
> 
> @xiaoshir very good idea to use online logo generators. I think it is a good way to find inspiration, and if your team find something that better suits than my propositions, fell absolutely free to use it ! I am just offering my free time because I enjoy drawing :)

Dear Lisa, 

Pls don't get me wrong....I very much like your design and only proposed the logo generator for, as you mentioned, inspirations purpose. While such tool provides many variations, logos generated automatically do have a "machine" taste, which is not comparable with something designed by a human like you:) 

As for the slogan, I also just wrote "open and reproducible" as an example, meaning: we could discuss whether to include this or not at all, and the content is also open to other ideas. To me, LCA results generated by more conventional tools like Simapro or Gabi are also reproducible in a way, but when I wrote reproducible, I mean documentation from raw data to activity flows at process level can be transparently documented using either excel formulas/script in Jupyter notebooks. How could we make this meaning more explicit? Maybe we could consider "tracible"? or "trackable"? The other word I thought about is "interactive", which again can be achieved by the combination and conventional LCA tool and an interactive graphic  maker/viewer. But Brightway, being python-based itself, is just more handy/intuitive to be combined with other python-based graphing package like [plotly](https://plotly.com/) to generate interactive results more easily.

**Comment by xiaoshir** [comment]
For font, personally I use "[Helvetica](https://www.fonts.com/font/linotype/helvetica)" a lot, which is flat, round and clear to read. Not sure if @cmutel would like to credit the Swiss flavor of Brightway a bit (i.e. developed in Switzerland, and also partially funded by Swiss research fundings)? :P If yes, this could be an option:)

**Comment by cmutel** [comment]
@LisaDuval Thanks a lot for the iteration.

I have let this sink in for a few days, but my first impression has stayed the same - Cuyabara is a bit too much. I like the idea, but not this execution. Let's stick with Roboto, this works fine.

I don't think we need a phrase in the logo, we can add this to the homepage/merchandise if we want later on.

@xiaoshir To me, being more reproducible is a big goal of current development, but it is hard. We need better logging, and probably even the export of something like an environment file with library versions, hashes of data, etc. to allow calculations to be easily and 100% reproduced. This is not as simple as it could be.

**Comment by LisaDuval** [comment]
Ok, I send you by e-mail the final package. Thank you everyone for the feedbacks and support !

**Comment by cmutel** [comment]
https://github.com/brightway-lca/logo
