### ISSUE TITLE
Brightway webpage template and design guideline

### ISSUE THREAD

**Issue by cmutel** [Depart-de-Sentier/Prizes#3]
# Summary

The Brightway webpage needs a refresh. We should take advantage of our [new logo](https://github.com/brightway-lca/logo) to both change the color scheme, but also have the main webpage be the first page of the documentation. Therefore, we need a **sphinx template** for the Brightway webpage/documentation.

# Prize Amount

100 CHF or EUR

# Output

Sphinx template and example implementation (as a GH repo or similar) which has the following attributes:

* Three-column layout following examples given by [Tomas](https://github.com/Depart-de-Sentier/Prizes/issues/2#issuecomment-1077682124).
* Responsive layout.
* Example implementation is built from ReST (can include dummy content) using standard sphinx tools. Common plugins are allowed.
* Design document with colors and fonts. Styling should be provided for at least 3 heading levels, text, code samples, tables, links, and any other common HTML attributes.

Reuse of existing templates is highly encouraged! Use of CC or similar licensed templates is fine.

# Verification

Verification will be done by @cmutel and @tngTUDOR

**Comment by tngTUDOR** [comment]
Bonus points for solutions taking into account a global documentation view, like https://diataxis.fr/?s=09 for example.

**Comment by cmutel** [comment]
@tngTUDOR Excellent suggestion. I originally thought you meant we need to support multiple languages, which is also true...

**Comment by cmutel** [comment]
Closing this, we will use Furo and MyST.
